import Head from 'next/head';
import type { AppProps } from 'next/app'

// Styles
import GlobalStyles from '../styles/globals';

import { useEffect } from 'react';

// Suspense
import { Suspense } from "react";


function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={<h1>Loading...</h1>}>
        <GlobalStyles />
        <Component {...pageProps} />
      </Suspense>
    </>
  )
}


export default App;